### ISSUE TITLE
Spaces not allowed in payment reference prefix

### ISSUE THREAD

**Issue by browningjp** [Jon-Salmon/Durham-Hires#13]

**Comment by Jon-Salmon** [comment]
I'd of thought that spaces shouldn't be aloud in the prefix at all to make it prefix clearer?

In this case spaces shouldn't be aloud when setting the prefix, suggestion to replace all whitespace with underscore?

**Comment by browningjp** [comment]
I'd say only restrict it as much as the banking system restricts them. Collingwood's current system is "TECH XX" with a space, I don't think that's particularly unclear?

**Comment by Jon-Salmon** [comment]
Fair enough, how does this sound:

- Prefixes can be any string

- When comparing booking references when treasurer submits payment, all spaces and cases are ignored.

**Comment by browningjp** [comment]
Yes, I think that's the best way to do it. Doesn't need to be an exact match for the treasurer side of things.

Perhaps we could also give the treasurers a view showing the outstanding hire IDs and amounts due, so they can spot any obvious typos that hirers have made in the payment reference?

**Comment by Jon-Salmon** [comment]
This should be implemented now, will open new ticket for expanding treasurer system
