### ISSUE TITLE
Discount codes

### ISSUE THREAD

**Issue by browningjp** [Jon-Salmon/Durham-Hires#15]
to allow 'guests' to get a discount (e.g. free hire for users of Assembly Rooms)

**Comment by Jon-Salmon** [comment]
Added a basic implementation. Current limitations are
 - Codes cannot expire
 - Codes can have indefinite usage until removed by admin
 - Only one code per booking can be used

Currently added to [staging](https://hires.jon-salmon.me) server for testing
