### ISSUE TITLE
Ability to add arbitrary pages and file uploads (e.g. radio mic paperwork)

### ISSUE THREAD

**Issue by browningjp** [Jon-Salmon/Durham-Hires#16]

**Comment by Jon-Salmon** [comment]
Maybe add a 'docs' table with the following columns: Id, Site, File (reference to stored file), DisplayName??, Item

If item is 0 file is site wide, if item > 0 file is associated with that catalog item?

**Comment by browningjp** [comment]
Only a very minor thing, but might be easier to understand (if anyone is ever poking around in the database) if we set the 'item' column to NULL for a site-wide item
