### ISSUE TITLE
HTML WYSIWYG editor on item details

### ISSUE THREAD

**Issue by browningjp** [Jon-Salmon/Durham-Hires#17]
e.g. for bold text, links to user manual etc

**Comment by Jon-Salmon** [comment]
Should be very doable as already set up to display details with html tags.
Also WYSIWYG editor module already present elsewhere

**Comment by Jon-Salmon** [comment]
I think this is now implemented, A little testing is required then will close

**Comment by Jon-Salmon** [comment]
Not saving some formatting (eg bold, underline)
