### ISSUE TITLE
Error when hiring only one item

### ISSUE THREAD

**Issue by browningjp** [Jon-Salmon/Durham-Hires#4]
If only hiring one item, you can't submit the order.

When adding items to your order, it creates a new hidden input named "id[]", however, this will only create an array (on the PHP side) if there ends up being more than one item in the array, otherwise I think it's just a direct value.

Should be quite easy to check to see if `$request->id ` is an array before calling `foreach($request->id)` on BookingController.php line 393

**Comment by Jon-Salmon** [comment]
Fixes as far as I can tell
