### ISSUE TITLE
Confirm popup when deleting bookings

### ISSUE THREAD

**Issue by Jon-Salmon** [Jon-Salmon/Durham-Hires#41]

**Comment by CJEBond** [comment]
Would be good to have more confirmations in general, including for deleting catalog items.

**Comment by Jon-Salmon** [comment]
Confirms have been added for:
 - Deleting items, categories, templates, internal bookings and external bookings
 - Refreshing the calendar authentication token

See commit 0fe80ea36475bec5a2ff1a94308e4436906dc9a6

**Comment by CJEBond** [comment]
Tested, working:
-Calendar
-Categories
-Items
-Internal booking
-Templates
-External booking
